// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: record.sql

package db

import (
	"context"
)

const createRecord = `-- name: CreateRecord :one
INSERT INTO records (
  trader_id,
  amount
) VALUES (
  $1, $2
) RETURNING id, trader_id, amount, created_at
`

type CreateRecordParams struct {
	TraderID int64 `json:"trader_id"`
	Amount   int64 `json:"amount"`
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, createRecord, arg.TraderID, arg.Amount)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.TraderID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getRecord = `-- name: GetRecord :one
SELECT id, trader_id, amount, created_at FROM records
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRecord(ctx context.Context, id int64) (Record, error) {
	row := q.db.QueryRowContext(ctx, getRecord, id)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.TraderID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listRecords = `-- name: ListRecords :many
SELECT id, trader_id, amount, created_at FROM records
WHERE trader_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListRecordsParams struct {
	TraderID int64 `json:"trader_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListRecords(ctx context.Context, arg ListRecordsParams) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, listRecords, arg.TraderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.TraderID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
